# Generated by Django 2.1.7 on 2025-07-05 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/uploaded/')),
                ('interview_video', models.FileField(blank=True, null=True, upload_to='media/interviews/')),
                ('score', models.FloatField(default=0)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('score', models.FloatField(default=0)),
                ('interview_video', models.FileField(blank=True, null=True, upload_to='media/interviews/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField()),
                ('video_file', models.FileField(blank=True, null=True, upload_to='media/interviews/')),
                ('communication_score', models.IntegerField(default=0)),
                ('relevance_score', models.IntegerField(default=0)),
                ('confidence_score', models.IntegerField(default=0)),
                ('total_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(upload_to='resumes/uploaded/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='analyzerapp.Candidate')),
            ],
        ),
    ]
