# Generated by Django 2.1.7 on 2026-06-12 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzerapp', '0002_candidate_interview_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_rating', models.PositiveSmallIntegerField(default=3)),
                ('platform_rating', models.PositiveSmallIntegerField(default=3)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='analyzerapp.Candidate')),
            ],
        ),
    ]
