# Generated by Django 2.1.7 on 2026-06-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzerapp', '0003_userfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ai_result',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='interview_transcript',
            field=models.TextField(blank=True),
        ),
    ]
